// <auto-generated />
namespace проект.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFileld : IMigrationMetadata
    {
        public readonly ResourceManager Resources = new ResourceManager(typeof(AddFileld));
        
        string IMigrationMetadata.Id
        {
            get { return "202312061812470_AddFileld"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
